import Head from 'next/head'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="wrapper">
				<h1>오늘의 추천메뉴</h1>
				<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nostrum sit, error obcaecati assumenda minima vitae eaque quibusdam officiis nemo quasi dolores sint magni exercitationem at, dolorum expedita nisi dignissimos voluptates!</p>
			</main>
		</div>
	)
}